apiVersion: v1
kind: ReplicationController
metadata:
  name: api
  labels:
    name: api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: wozzup
          image: docker.pkg.github.com/danielmbaluka/wozzup/wozzup:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8009
      imagePullSecrets:
        - name: regcred